import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900">
        <Header /> {/* 🔹 Standardized Header */}
        <main className="container mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}

// 🔹 Updated Header Component with Larger Logo
function Header() {
  return (
    <header className="bg-white shadow-md py-4">
      <div className="container mx-auto flex items-center">
        <img
          src="https://thatdisabilityadventurecompany.com.au/icons/logo.webp"
          alt="TDAC Logo"
          className="h-18 w-auto ml-4" // ✅ Left-aligned with slight indentation (margin-left: 16px)
        />
      </div>
    </header>
  );
}
